// <auto-generated />
using System;
using Geopolitics.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Geopolitics.Infrastructure.Migrations
{
    [DbContext(typeof(GeopoliticsDbContext))]
    [Migration("20260911195314_LocationPrecision")]
    partial class LocationPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Geopolitics.Domain.AiInference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<double>("LatencyMilliseconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ObservationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StructuredOutput")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ObservationId");

                    b.HasIndex("Outcome", "CreatedAt");

                    b.ToTable("ai_inferences", (string)null);
                });

            modelBuilder.Entity("Geopolitics.Domain.GeopoliticalIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("ClassificationConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ClassificationMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("EntityKeys")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_keys");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObservationCount")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("ObservationIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("observation_ids");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("EventType", "OccurredAt");

                    b.HasIndex("Severity", "OccurredAt");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("Geopolitics.Domain.RawObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("ClassificationConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ClassificationMethod")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedLanguage")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DuplicateOfObservationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationResolutionNote")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelSeverity")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double?>("ModelSeverityConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<long?>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReceivedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeverityRationale")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIdentifier")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique()
                        .HasFilter("Status <> 'Duplicate'");

                    b.HasIndex("IncidentId");

                    b.HasIndex("ReceivedAt");

                    b.ToTable("observations", (string)null);
                });

            modelBuilder.Entity("Geopolitics.Domain.GeopoliticalIncident", b =>
                {
                    b.OwnsOne("Geopolitics.Domain.GeoLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("GeopoliticalIncidentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CountryCode")
                                .HasMaxLength(8)
                                .HasColumnType("TEXT")
                                .HasColumnName("location_country_code");

                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL")
                                .HasColumnName("longitude");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("location_name");

                            b1.Property<string>("Precision")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("location_precision");

                            b1.HasKey("GeopoliticalIncidentId");

                            b1.HasIndex("Latitude", "Longitude");

                            b1.ToTable("incidents");

                            b1.WithOwner()
                                .HasForeignKey("GeopoliticalIncidentId");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Geopolitics.Domain.RawObservation", b =>
                {
                    b.OwnsMany("Geopolitics.Domain.ExtractedEntity", "Entities", b1 =>
                        {
                            b1.Property<Guid>("RawObservationId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(120);

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(30);

                            b1.HasKey("RawObservationId", "__synthesizedOrdinal");

                            b1.ToTable("observations");

                            b1
                                .ToJson("entities")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("RawObservationId");
                        });

                    b.OwnsOne("Geopolitics.Domain.GeoLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("RawObservationId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CountryCode")
                                .HasMaxLength(8)
                                .HasColumnType("TEXT")
                                .HasColumnName("location_country_code");

                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL")
                                .HasColumnName("longitude");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("location_resolved_name");

                            b1.Property<string>("Precision")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("location_precision");

                            b1.HasKey("RawObservationId");

                            b1.ToTable("observations");

                            b1.WithOwner()
                                .HasForeignKey("RawObservationId");
                        });

                    b.Navigation("Entities");

                    b.Navigation("Location");
                });
#pragma warning restore 612, 618
        }
    }
}
